# Generated by Django 6.0.3 on 2026-04-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mario Marku', max_length=100)),
                ('description', models.TextField(help_text='The main text on your home page. HTML is allowed.')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('pypi_url', models.URLField(blank=True, null=True, verbose_name='PyPI URL')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/main/')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image/GIF.', null=True, upload_to='projects/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='OR paste a YouTube URL.', null=True)),
                ('video_id', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('blocked_embed', models.BooleanField(default=False, help_text='Check this if YouTube blocks embedding.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='my_portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Media',
                'verbose_name_plural': 'Project Media',
            },
        ),
    ]
