# Generated by Django 6.0.3 on 2026-03-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_project_main_image_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
