# Generated by Django 6.0.3 on 2026-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_remove_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief one-sentence summary (italicized on page).', max_length=300),
        ),
    ]
