# Generated by Django 6.0.3 on 2026-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pypi_url',
            field=models.URLField(blank=True, null=True, verbose_name='PyPI URL'),
        ),
    ]
