# Generated by Django 6.0.3 on 2026-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0005_project_pypi_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['order', 'label']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the menu.'),
        ),
        migrations.AddField(
            model_name='resume',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the menu.'),
        ),
    ]
