# Generated by Django 6.0.3 on 2026-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_alter_project_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube link here (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
    ]
