# Generated by Django 6.0.3 on 2026-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0007_projectimage_youtube_url_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste any YouTube link here.', null=True),
        ),
    ]
