# Generated by Django 6.0.3 on 2026-03-31 20:35

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0008_alter_projectimage_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Paste any YouTube link here.', null=True),
        ),
    ]
