# Generated by Django 6.0.3 on 2026-03-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0009_remove_projectimage_youtube_url_projectimage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='video',
            field=models.URLField(blank=True, help_text='Paste any YouTube link.', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
