# Generated by Django 6.0.3 on 2026-03-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0010_alter_project_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='video',
        ),
    ]
